### ISSUE TITLE
Bug? Board related? WiFi settings ignored.

### ISSUE THREAD

**Issue by xanathon** [JeanetteMueller/Huyang_Remote_Control#1]
If I compile and upload to ESP8266 WiFi settings in config.h are ignored.

The WiFi SSDI is "FaryLink_F5A08B" and no password.

I tested if the config.h file is read at all by changing the port to 8080 and that works, but the SSID and password settings are completely ignored. Everything else seems to work, since I get the web interface (I have not yet connected the LCD screens).

Any ideas? The board is an 8266 NodeMCU LUA Amica V2 .

TIA! And thanks for your work on this.

**Comment by JeanetteMueller** [comment]
Hi. From when is your version? I did a lot of updates today. Please check it out. 
Never tested WiFi without password. Will check this.

**Comment by xanathon** [comment]
I guess I cloned yesterday.

I did not want to use no password. I did set SSID and PW in the config.h but both are ignored.

I'll do a pull and try again.

**Comment by xanathon** [comment]
I just pulled the new version. SSID and password settings in config.h are still ignored.

**Comment by JeanetteMueller** [comment]
Has you config.h the wifi Mod parameter?

**Comment by xanathon** [comment]
WiFiMode? Yes, it's set to 0

**Comment by JeanetteMueller** [comment]
I have to ask: how do you get the webinterface if SSID and password are ignored. What is your expectation?
With Mode = 0 it is an accesspoint with the given SSID. If you want to be accessible via your home WiFi you should try Mode 1.

**Comment by xanathon** [comment]
As I wrote above: The ESP board creates a WiFi access point with the SSID "FaryLink_F5A08B", I did not enter that SSID and have no idea where it comes from. I do NOT want it to be accessible via the Home network, I want it to create it's own access point. I did set the mode to "0" and I did set the WiFi credentials in the config.h file, they are completrely ignored. As I wrote above. The config.h file seems to be read, though, because I changed the port of the webserver to 8080 and that worked. So to me this looks like a problem with the WiFi configuration settings being ignored.

My expectation: I set a SSID and a password in the config.h and both are used (instead of "FaryLink_F5A08B" and no password).

my config.h (password redacted):

```
// Install Libraries
// Please read the "README.md"


// Huyang Wifi Modes 
// 0 = creates his own wifi with the following Data
// 1 = connects to a existing wifi with the following credentials
#define WiFiMode 0

// To get this running, change the WifiSsid to whatever your wifi should be called
// this Wifi will be created by Huyang himself. Don' name this like your home Wifi.
#define WifiSsid "HuyangWifiControl" // <- change if needed

// set a custom passwort so not everyone can control your Huyang Droid
#define WifiPassword "mypassword"



// ONLY if the Huyang Wifi Mode is 0:
// The Webserver is per default accessible via 192.168.10.1
IPAddress apIP(192, 168, 10, 1);
#define ServerPort 8080
// If you change the Port to something different than 80, like 301
// Huyang will be accessible via 192.168.10.1:301

// ONLY if the Huyang Wifi Mode is 1:
// Conenct to your Wifi Router and check the connected Devices to get his IP Adress
// When connected wia USB, the console will write down the current IP Adress 3 times on bootup
```

**Comment by JeanetteMueller** [comment]
#define WifiSsid "HuyangWifiControl" // <- change if needed
is this your current config? you did not changed the SSID

**Comment by xanathon** [comment]
Correct. I only changed the password.

**Comment by JeanetteMueller** [comment]
and without changing this, you stil see no "HuyangWifiControl" Wifi with your devices but the "FaryLink_F5A08B"?
and you get the webinterface when connected to "FaryLink_F5A08B"? 
VERY Strange. i think it is a thing with your board. 
i can later check the documents of this board.

**Comment by xanathon** [comment]
Correct.

I got it from AZ Delivery (had some of them lying around from an earlier project), the board type is in the opening post. That may be a strange error, since everything else works as expected.

**Comment by JeanetteMueller** [comment]
yes, strange. Because i use this since weeks and everything works as expected. as accesspoint and in the Mode = 1 way to connect it to the local wifi.
