### ISSUE TITLE
i can't compile

### ISSUE THREAD

**Issue by Stanyshboy** [JeanetteMueller/Huyang_Remote_Control#11]
hi i get this error, what i've to do?
:

C:\Users\stany\Documents\Arduino\Huyang_Remote_Control\src\classes\HuyangAudio\HuyangAudio.cpp: In constructor 'HuyangAudio::HuyangAudio()':
C:\Users\stany\Documents\Arduino\Huyang_Remote_Control\src\classes\HuyangAudio\HuyangAudio.cpp:8:26: error: no matching function for call to 'SoftwareSerial::SoftwareSerial()'
    8 | HuyangAudio::HuyangAudio()
      |                          ^
In file included from C:\Users\stany\Documents\Arduino\Huyang_Remote_Control\src\classes\HuyangAudio\HuyangAudio.h:4,
                 from C:\Users\stany\Documents\Arduino\Huyang_Remote_Control\src\classes\HuyangAudio\HuyangAudio.cpp:1:
C:\Users\stany\Documents\Arduino\Huyang_Remote_Control\src\classes\HuyangAudio\SoftwareSerial.h:92:3: note: candidate: 'SoftwareSerial::SoftwareSerial(uint8_t, uint8_t, bool)'
   92 |   SoftwareSerial(uint8_t receivePin, uint8_t transmitPin, bool inverse_logic = false);
      |   ^~~~~~~~~~~~~~
C:\Users\stany\Documents\Arduino\Huyang_Remote_Control\src\classes\HuyangAudio\SoftwareSerial.h:92:3: note:   candidate expects 3 arguments, 0 provided
C:\Users\stany\Documents\Arduino\Huyang_Remote_Control\src\classes\HuyangAudio\SoftwareSerial.h:50:7: note: candidate: 'constexpr SoftwareSerial::SoftwareSerial(const SoftwareSerial&)'
   50 | class SoftwareSerial : public Stream
      |       ^~~~~~~~~~~~~~
C:\Users\stany\Documents\Arduino\Huyang_Remote_Control\src\classes\HuyangAudio\SoftwareSerial.h:50:7: note:   candidate expects 1 argument, 0 provided
C:\Users\stany\Documents\Arduino\Huyang_Remote_Control\src\classes\HuyangAudio\HuyangAudio.cpp:10:27: error: 'SWSERIAL_8N1' was not declared in this scope; did you mean 'SERIAL_8N1'?
   10 |  _audioSerial.begin(9600, SWSERIAL_8N1, AudioSerialPort_RX, AudioSerialPort_TX);
      |                           ^~~~~~~~~~~~
      |                           SERIAL_8N1

exit status 1

Compilation error: no matching function for call to 'SoftwareSerial::SoftwareSerial()'

**Comment by JeanetteMueller** [comment]
please replace the whole project except the config.h
the Missing Software shoud be part of the expressif compiler files. 
What board did you select?

**Comment by Stanyshboy** [comment]
> please replace the whole project except the config.h the Missing Software shoud be part of the expressif compiler files. What board did you select?

node mcu 1.0

**Comment by JeanetteMueller** [comment]
try "Generic esp8266 module"
you are using the esp8266? or do you use the d1 mini? 
do u use the custom pcb?

**Comment by Stanyshboy** [comment]
solved just........rebooting the pc!
I don't know what's happened, but suddenly everything worked.

Thanks
