### ISSUE TITLE
Getting it to work

### ISSUE THREAD

**Issue by cmcooper1971** [JeanetteMueller/Huyang_Remote_Control#6]
Hi All,

Thanks to Jeanette for the code, however I am struggling to get this to compile.

I have loaded the following libraries:

Arduino GFX Library
ESPAsyncWebServer

Although the instructions do not mention, I have also loaded the following post errors during the compile

Adafruit-PWM-Servo-Driver-Library
JxWifiManager

However, none of this has resulted in a complete compile.

The code I was given for the sketch is as follows:

```
// HOW TO Get this running!!!
// open config.h and edit the configuration as you need it

#include <Arduino.h>
#ifdef ESP32
#include <WiFi.h>
#include <AsyncTCP.h>
#elif defined(ESP8266)
#include <ESP8266WiFi.h>
#endif

#include "config.h"

#include <Arduino_GFX_Library.h>
#include "src/classes/HuyangFace/HuyangFace.h"

Arduino_DataBus *leftBus = new Arduino_HWSPI(0 /* DC */, 15 /* CS */);
Arduino_GFX *leftEye = new Arduino_GC9A01(leftBus, 0 /* RST */);

Arduino_DataBus *rightBus = new Arduino_HWSPI(0 /* DC */, 16 /* CS */);
Arduino_GFX *rightEye = new Arduino_GC9A01(rightBus, 0 /* RST */);

HuyangFace *huyangFace = new HuyangFace(leftEye, rightEye);

#include "src/wifi/Wifi.h"
#include "src/webserver/WebServer.h"

void setup() {
  Serial.begin(115200);  //Used only for debugging on arduino serial monitor
  Serial.println(F("Huyang! v1.2"));

  setupWifi();

  setupWebserver();

  huyangFace->setup();

  Serial.println(F("setup done"));
}

void loop() {

  loopWifi();

  loopWebserver();

  huyangFace->loop();
}

```

**Comment by JeanetteMueller** [comment]
did you collect some rows from my code? 
this is not what I released. 
please download the release ZIP

**Comment by cmcooper1971** [comment]
I have downloaded your release, but the sketch INO is blank and doesnt have a setup, loop, variables etc.

The code above was supplied to me, as they couldnt get it working. I am just trying to help a friend.

**Comment by JeanetteMueller** [comment]
inside of the ino there are a lot of includes. the logic is there
it is important to include it in a precise order

**Comment by cmcooper1971** [comment]
Thank you, I saw them.

To check, what IDE framework are you using as Im using Arduino 2.0?

**Comment by JeanetteMueller** [comment]
To Edit the Code i am using Visual Studio Code but to Programm i use Arduino 2.x as usual... 
The Files should look like this. with subdirectories:

<img width="643" alt="Bildschirmfoto 2024-09-19 um 18 01 10" src="https://github.com/user-attachments/assets/daf9738a-6842-4486-b17c-1b6bbfdb00b3">

**Comment by cmcooper1971** [comment]
Thank you. That is exactly how mine looks from your library file.  Within Visual Studio Code, what extensions are you using? How can you programme with the Arduino IDE, when there is no setup or loop within the INO file?

Sorry to be so questioning, but I have been asked to get your code operational for an event next Saturday (https://nor-con.co.uk/).

If I can't get this working, I will have to write the software for the eyes as that is all my friend needs which is easy enough, but we would prefer to use your software.

**Comment by JeanetteMueller** [comment]
inside the src/system.h you can find the setup and loop.

**Comment by JeanetteMueller** [comment]
Version 1.9 will be configurable so you can disable neck and body movements. this results in a smaller webinterface because interface that is not needed will not be shown. 
will be released very soon.
