### ISSUE TITLE
web interface not complete

### ISSUE THREAD

**Issue by Stanyshboy** [JeanetteMueller/Huyang_Remote_Control#7]
I installed the software following instructions, but i get only part of the interface as showed in the pic
The phone is a Samsung fold 4

![Screenshot_20241115_191029_Chrome](https://github.com/user-attachments/assets/3fff490a-5340-4b8e-a090-6bd9bce874c5)

**Comment by JeanetteMueller** [comment]
fixed with 1.9. Please update
