### ISSUE TITLE
JwWifiManager Error

### ISSUE THREAD

**Issue by Myrddinwylit** [JeanetteMueller/Huyang_Remote_Control#9]
Don't know why i am getting the following error
Compilation error: 'class JxWifiManager' has no member named 'getCurrentIPAdress'

**Comment by JeanetteMueller** [comment]
where did you get the JxWifiManager? was it inside of the 1.9 zip or from separate installation?

**Comment by JeanetteMueller** [comment]
please use the one inside of the zip file. or update from github

**Comment by Myrddinwylit** [comment]
that was it - must have had an older version
